/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projecytl.Enums;

/**
 *
 * @author AlbertoRS
 */
public enum DescriptionRunesPrimary {
    //Precision
    ConquerorDescription("Ranged basic attacks on-hit against enemy champions grant 1 stack of Conqueror, while Melee role melee basic attacks on-hit grant 2 stacks. Abilities that deal damage to an enemy champion always grant 2 stacks."),
    PressTheAttackDescription("Basic attacks against enemy Champion icon champions apply stacks for 4 seconds. Attacking a new target removes all stacks from the previous target. The third stack consumes them all to deal 40 − 180 (based on level) bonus Attack damageAbility power Adaptive damage and makes them Exposed for 6 seconds, causing them to take 8% − 12% (based on level) increased damage from all subsequent sources (except from Hybrid penetration true damage)."),
    LethalTempoDescription("After 1.5 seconds upon damaging an enemy Champion icon champion you gain Attack speed icon 40% − 110% (based on level) bonus attack speed as well as have any bonus attack speed ignore the attack speed cap for 3 seconds. Attacking a champion while the effect is active will extend the duration to 6 seconds."),
    FleetFootworkDescription("Moving and basic attacking generates Energize stacks, up to 100. FLEET FOOTWORK: When fully Kircheis Shard item Energized, your next basic attack Heal power restores 3 − 60 (based on level) (Attack damage icon + 30% bonus AD) (Ability power icon + 30% AP) Health icon health and grants Movement speed icon 20% bonus movement speed for 1 second. On Ranged role ranged champions, the healing is only 20% effective versus Minion icon minions."),
    //Domination
    ElectrocuteDescription("Basic attacks, abilities, item effects and summoner spells generate stacks on enemy Champion icon champions hit, up to one per attack or cast. Applying 3 stacks to a target within a 3 second period causes them to be struck by lightning, dealing them 30 − 180 (based on level) (+ 40% bonus AD) (+ 25% AP) Attack damageAbility power Adaptive damage."),
    PredatorDescription("Channels for 1.5 seconds. You can move while channeling and the Channeling icon channel will be Silence icon interrupted if you cast an ability or enter combat (except Minion icon minions), putting the item on a 50% Cooldown reduction icon cooldown. Activating Predator will not break Guerrilla Warfare stealth."),
    DarkHarvestDescription("Dealing (non-Umbra Blades periodic) damage to a Champion icon champion below 50% of their maximum health deals 20 − 60 (based on level) (+ 5 per Soul) (+ 25% bonus AD) (+ 15% AP) bonus Attack damageAbility power Adaptive damage and reaps 1 Soul. This cannot occur again for 45 seconds, resetting to 1.5 seconds on champion Damage rating takedown."),
    HailOfBladeDescription("Basic attacking an enemy Champion icon champion grants Attack speed icon 110% bonus attack speed as well as make your bonus attack speed ignore the attack speed cap (2.5) for your next 3 basic attacks on-attack. Attack resets do not consume a stack of Hail of Blades, but do benefit from the bonus attack speed."),
    //Sorcery
    SummonAeryDescription("Basic attacks, abilities, item effects, and summoner spells against an enemy Champion icon champion signals Aery to dash to them, dealing 10 − 40 (based on level) (+ 15% bonus AD) (+ 10% AP) Attack damageAbility power Adaptive damage. Heal power Healing, shielding, or buffing an ally signals Aery to dash to them, Hybrid resistances icon shielding them for 35 − 80 (based on level) (+ 40% bonus AD) (+ 25% AP) for 2 seconds."),
    ArcaneCometDescription("Damaging an enemy Champion icon champion with an ability Projectile hurls an Arcane Comet at their current location, dealing 30 − 100 (based on level) (+ 35% bonus AD) (+ 20% AP) Attack damageAbility power Adaptive damage after a brief delay."),
    PhaseRushDescription("Basic attacks, abilities, item effects and summoner spells generate stacks on enemy Champion icon champion hit, up to one per attack or cast. Applying 3 stacks to a target within a 4 second period grants you 40% − 60% (based on level) Movement speed icon movement speed and 75% Slow immune icon slow resist for 3 seconds."),
    //Resolve
    GraspOfTheUndyingDescription("Entering combat generates one stack every second for the next 3 seconds. Additional stacks may be generated by re-entering combat after 2 seconds. After reaching 4 stacks, your next basic attack within 6 seconds against an enemy Champion icon champion consumes all stacks to deal 4% of your maximum health in Magic damage bonus magic damage, restore 2% of your Health icon maximum health, and permanently grant 5 bonus health. The empowered attack duration refreshes whenever going in combat."),
    AftershockDescription("Immobilizing an enemy Champion icon champion grants a static 35 (+ 80% bonus armor) bonus armor and 35 (+ 80% bonus magic resistance) bonus magic resistance for 2.5 seconds. The bonus resistances are capped at 80 − 150 (based on level)."),
    GuardianDescription("While within 175 units of an allied Champion icon champion, you raise your Guard. Allied champions you affect with unit-targeted abilities are also Guarded for 2.5 seconds, regardless of distance."),
    //Inspiration
    GlacialAugmentDescription("Basic attacks Slow icon slow enemy Champion icon champions for 2 seconds, which increases over the duration. This effect cannot occur on the same target more than once every few seconds.\n"
            + "Melee role Melee champions: 45% − 55% (based on level) maximum slow.\n"
            + "Ranged role Ranged champions: 30% − 40% (based on level) maximum slow."),
    UnsealedSpellbookDescription("While not channeling Teleport Teleport and being out-of-combat for 5 seconds, swap one of your equipped summoner spells to a new, single use summoner spell. You cannot select a summoner spell you have already equipped."),
    PrototypeVersatilityDescription("Periodically grants a single use of another random keystone. 5 − 3 (based on level) second cooldown between using a keystone and gaining the next (9 − 7 (based on level) seconds for Ranged role ranged champions). After 40 seconds of not using a given keystone, another random keystone is granted while out of combat. Entering the fountain will re-roll the current keystone.");
    private String ru;

    private DescriptionRunesPrimary(String r) {
        this.ru = r;
    }

    public String getRune() {
        return ru;
    }

}
